WissenTours.Management.Presentation/Models/ErrorViewModel.cs
using System;

namespace WissenTours.Management.Presentation.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WissenTours.Management.Presentation/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WissenTours.Management.Application.Cities;

namespace WissenTours.Management.Presentation.Controllers
{
    //Loosely Coupling VS Tightly Coupling
    public class CityController : Controller
    {
        private readonly ICityService _cityService;
        // Ben bu interface'ın concret'ini nereden alıcam diyor constructor
        //Startup dosyasındaki metot bu interface'in concrate sınıfını soyler ...!
        public CityController(ICityService cityService)
        {
            _cityService = cityService;
        }


        public IActionResult Index()
        {
            //Service
            //Aslında çok genel bir ifade, ama yine de Business/Application katmanında islemlerin yapıldıgı nesnelere verilen isim 
            //CityService
            //StationService

            //Bu iş yapılsın kimin yaptıgı onemli degil
            var cities = _cityService.GetAll();

            return View(cities);
        }

        public IActionResult GetById(int id)
        {
            var city = _cityService.GetById(id);
            if (city != null)
            {
                return View(city);
            }
            else
            {
                return Content("kayıt bulunamadı");
            }
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CityDTO city)
        {
            _cityService.Create(city);
            return RedirectToAction("Index");
        }

        public IActionResult Update(int id)
        {
            var city = _cityService.GetById(id);
            return View(city);
        }

        [HttpPost]
        public IActionResult Update(CityDTO city)
        {
            if (city != null)
            {
                _cityService.Update(city);

                return RedirectToAction("Index");
                //return View(city);
            }
            return Content("Hatalı işlem");
        }

        public IActionResult Delete(CityDTO cityDTO)
        {
            if (cityDTO != null)
            {
                var city = _cityService.GetById(cityDTO.Id);
                _cityService.Delete(city);
                return RedirectToAction("Index");
            }
            return Content("Silinecek kayıt bulunamadı");
        }




    }
}

WissenTours.Management.Presentation/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WissenTours.Management.Presentation.Models;

namespace WissenTours.Management.Presentation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WissenTours.Management.Presentation/Views/City/Create.cshtml
<div class="row">
    <div class="col-12 col-md-8">
        <form method="post">
            <label class="form-label" for="Name">City Name</label>
            <input type="text" name="Name" class="form-control" />
            <button class="btn btn-success mt-3" type="submit">Save</button>
        </form>
    </div>
</div>

WissenTours.Management.Presentation/Views/City/GetById.cshtml
@model CityDTO

<div class="row">
    <div class="col-sm-8">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>@Model.Id</td>
                    <td>@Model.Name</td>
                </tr>
            </tbody>
        </table>

    </div>

</div>

WissenTours.Management.Presentation/Views/City/Index.cshtml
@* using calısmaz burda bunun icin View import'a git Views klasorunun altında *@


@model IEnumerable<CityDTO>

<div class="row">
    <div class="col-12 col-md-8">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>
                        <a class="btn btn-success" asp-action="Create">New City</a>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var city in Model)
                {
                    <tr>
                        <td>@city.Id</td>
                        <td>@city.Name</td>
                        <td>
                            <a class="btn btn-primary" asp-route-id=@city.Id asp-action="Update">Update</a>
                            <a class="btn btn-danger" asp-route-id=@city.Id asp-action="Delete">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div> 

WissenTours.Management.Presentation/Views/City/Update.cshtml
@model CityDTO

<div class="row">
    <div class="col-12 col-md-8">
        <form method="post">
            <label class="form-label" for="Name">City Name</label>
            <input type="text" name="Name" class="form-control" value=@Model.Name />
            <button class="btn btn-success mt-3" type="submit">Update</button>
        </form>
    </div>
</div>

WissenTours.Management.Presentation/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WissenTours.Management.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WissenTours.Management.Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WissenTours.Management.Presentation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WissenTours.Management.Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>